### ISSUE TITLE
Unable to launch game with this installed

### ISSUE THREAD

**Issue by pax-wax** [anviaan/CreateUnbreakableTools#4]
This mod just doesn't work at the moment, using Forge 47.2.6 with MC 1.20.1 and I only get kicked to the launcher without any crash log. I've tested this in an isolated instance with only this mod and create and found the exact same issue.

**Comment by andre-carbajal** [comment]
Use version 1.0 of the mod.
I'm checking what happened with version 1.1, it will be removed in the meantime.

**Comment by anviaan** [comment]
done!

**Comment by eligibbs** [comment]
Version 1.3 does the same thing for me, just released on the 18th on Curseforge, crashes my [pack](https://www.curseforge.com/minecraft/modpacks/phoenixtech-reloaded) with 1.3, have to keep on 1.2. Would love to be able to disable the explosions

**Comment by anviaan** [comment]
Can you show me the error message, to help you?

**Comment by eligibbs** [comment]
Sure, but theres no error/crash log like this issue Forge 47.3.12 for 1.20.1, here's the [latest.log](https://github.com/user-attachments/files/18224800/latest.log). Downgrading to 1.2 lets the pack load server and client side.

**Comment by eligibbs** [comment]
Just as an aside, as I don't believe it merits it's own issue, you might consider a weight for worldgen spawns in that config file, if it's not already there

**Comment by anviaan** [comment]
Version 1.3 crash should be fixed by now.
---
And talking about the terrain generation weight, I tried to add it in the configuration but the game always crashes because I can't set the terrain generation as a setting.

**Comment by eligibbs** [comment]
Sorry to bring bad news but went to update my pack to 1.4 for this and still have a crash. Does produce a crash report which I have 
[attached](https://github.com/user-attachments/files/18249615/crash-2024-12-25_23.41.44-client.txt) as well as the 
[logs](https://github.com/user-attachments/files/18249624/latest.log), but the crash report seems unhelpful. It mentions rendering errors and that's all I can take away. only change between the crash and no crash is 1.2 vs 1.4 for this mod. Again for a test environment, [here's my modpack](https://www.curseforge.com/minecraft/modpacks/phoenixtech-reloaded) that's being affected.

**Comment by anviaan** [comment]
An update will be released shortly and should fix the problem.
